{{- if .Values.gateway.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zeebe-cluster.names.gateway" . }}
  labels:
    {{- include "zeebe-cluster.labels.gateway" . | nindent 4 }}
  annotations:
    {{- toYaml  .Values.annotations | nindent 4 }}
{{- end -}}
