{{- if .Values.rbac.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "zeebe-cluster.names.broker" . }}
  labels:
    {{- include "zeebe-cluster.labels.broker" . | nindent 4 }}
    {{- toYaml  .Values.labels | nindent 4 }}
  annotations:
    {{- toYaml  .Values.annotations | nindent 4 }}
rules:
{{- if .Values.rbac.pspEnabled }}
  - apiGroups:
      - extensions
    resourceNames:
      - {{ include "zeebe-cluster.names.broker" . }}
    resources:
      - podsecuritypolicies
    verbs:
      - use
{{- end -}}
{{- end -}}
