{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zeebe-cluster.names.broker" . }}
  labels:
    {{- include "zeebe-cluster.labels.broker" . | nindent 4 }}
    {{- toYaml  .Values.labels | nindent 4 }}
  annotations:
    {{- toYaml  .Values.annotations | nindent 4 }}
{{- end -}}
